CREATE TABLE IF NOT EXISTS statistics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(128) NOT NULL,
  uri VARCHAR(128) NOT NULL,
  ip VARCHAR(16) NOT NULL,
  timestamp TIMESTAMP NOT NULL
);